# Generated by Django 2.2.6 on 2020-04-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Производитель')),
                ('country', models.CharField(blank=True, choices=[('china', 'China'), ('japan', 'Japan'), ('taiwan', 'Taiwan'), ('korea', 'Korea')], max_length=50, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('category', models.CharField(choices=[('note', 'notebook'), ('mon', 'monitor'), ('access', 'accessories')], max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='my_first_site.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
